meican:
  oauth2:
    client-id: Xqr8w0Uk4ciodqfPwjhav5rdxTaYepD
    client-secret: vD11O6xI9bG3kqYRu9OyPAHkRGxLh4E
  filter:
    dish-name-deny:
      - 辣
      - 菇
      - 排骨
    max-pay: 1500
    restaurant-deny:
      - 1234
    dish-deny:
      - 1234

