name: order-daily
on:
  workflow_dispatch:
    inputs:
      test:
        description: '只是测试而已'
        required: false
        default: 'ok'
  schedule:
    # 定时任务，在每天的19点30执行任务
    - cron: '30 11 * * *'
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: use cache to speed up the time of build
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: execute the task
        env:
          MEI_CAN_USERNAME: ${{ secrets.USER_NAME }}
          MEI_CAN_PASSWORD: ${{ secrets.PASSWORD }}
          MEI_CAN_COOKIE: ${{ secrets.COOKIE }}
          TENCENT_SMS_APP_ID: ${{ secrets.APP_ID }}
          TENCETN_SECRET_ID: ${{ secrets.SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          TENCENT_SMS_MESSAGE_TEMPLATE_ID: ${{ secrets.MESSAGE_TEMPLATE_ID }}
          TENCENT_SMS_SIGN: ${{ secrets.SIGN }}
          SATC_ORDER_PHONE: ${{ secrets.PHONE }}
        run: mvn install exec:java -Dexec.mainClass="cn.satc.order.AutoOrderApplication" -Dexec:classpathScope=runtime -DMEI_CAN_USERNAME=$MEI_CAN_USERNAME -DMEI_CAN_PASSWORD=$MEI_CAN_PASSWORD -DMEI_CAN_COOKIE=$DMEI_CAN_COOKIE -DTENCENT_SMS_APP_ID=$TENCENT_SMS_APP_ID -DTENCETN_SECRET_ID=$TENCETN_SECRET_ID -DTENCENT_SECRET_KEY=$TENCENT_SECRET_KEY -DTENCENT_SMS_MESSAGE_TEMPLATE_ID=$TENCENT_SMS_MESSAGE_TEMPLATE_ID -DTENCENT_SMS_SIGN=$TENCENT_SMS_SIGN -DSATC_ORDER_PHONE=$SATC_ORDER_PHONE