name: order-daily
on:
  schedule:
    # 定时任务，在每天的19点30执行任务
    - cron: '30 11 * * *'
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: use cache to speed up the time of build
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: execute the task
        env:
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          cookie: ${{ secrets.COOKIE }}
          appId: ${{ secrets.APP_ID }}
          secretId: ${{ secrets.SECRET_ID }}
          secretKey: ${{ secrets.SECRET_KEY }}
          messageTemplateId: ${{ secrets.MESSAGE_TEMPLATE_ID }}
          phone: ${{ secrets.PHONE }}
        run: mvn install exec:java -Dexec.mainClass="cn.satc.order.AutoOrderApplication"\
        -Dexec:classpathScope=runtime\
        -Dmeican.username=${username} -Dmeican.password=${password}\
        -DmeiCan.cookie=${cookie} -Dtencent.sms.appId=${appId} -Dtencent.sms.secretId=${secretId}\
        -Dtencent.sms.secretKey=${secretKey} -Dtencent.sms.messageTemplateId=${messageTemplateId}\
        -Dnotify.phone=${phone}
