name: order-daily
on:
  workflow_dispatch:
    inputs:
      test:
        description: '只是测试而已'
        required: false
        default: 'ok'
  schedule:
    # 定时任务，在每天的19点30执行任务
    - cron: '35 12 * * *'
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: use cache to speed up the time of build
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: execute the task
        env:
          MEI_CAN_USERNAME: ${{ secrets.USER_NAME }}
          MEI_CAN_PASSWORD: ${{ secrets.PASSWORD }}
          TENCENT_SMS_APP_ID: ${{ secrets.APP_ID }}
          TENCETN_SECRET_ID: ${{ secrets.SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          TENCENT_SMS_MESSAGE_TEMPLATE_ID: ${{ secrets.MESSAGE_TEMPLATE_ID }}
          TENCENT_SMS_SIGN: ${{ secrets.SIGN }}
          MEI_CAN_NOTIFY_PHONE: ${{ secrets.PHONE }}
        run: mvn install -Dmaven.test.skip=true exec:java -Dexec.mainClass="cn.satc.order.AutoOrderApplication" -Dexec:classpathScope=runtime -Dmeican.member.username=$MEI_CAN_USERNAME -Dmeican.member.password=$MEI_CAN_PASSWORD -Dmeican.member.notifu-phone=$MEI_CAN_NOTIFY_PHONE -Dtencent.sms.app-id=$TENCENT_SMS_APP_ID -Dtencent.sms.secret-id=$TENCETN_SECRET_ID -Dtencent.sms.secret-key=$TENCENT_SECRET_KEY -Dtencent.sms.template-id=$TENCENT_SMS_MESSAGE_TEMPLATE_ID -Dtencent.sms.sign=$TENCENT_SMS_SIGN